package main

import (
	"debug/pe"
	"encoding/binary"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	if len(os.Args) < 3 {
		fmt.Fprintf(os.Stderr, "usage: proxygen <dll-path> <output-dir> [trigger-func]\n")
		os.Exit(1)
	}

	dllPath := os.Args[1]
	outDir := os.Args[2]
	triggerFunc := "DllMain"
	if len(os.Args) >= 4 {
		triggerFunc = os.Args[3]
	}
	dllName := filepath.Base(dllPath)

	f, err := pe.Open(dllPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	exports, err := extractExports(f)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	if len(exports) == 0 {
		fmt.Fprintf(os.Stderr, "no named exports in %s\n", dllPath)
		os.Exit(1)
	}

	if triggerFunc != "DllMain" {
		found := false
		for _, e := range exports {
			if e == triggerFunc {
				found = true
				break
			}
		}
		if !found {
			fmt.Fprintf(os.Stderr, "error: trigger function %q not found in exports of %s\n", triggerFunc, dllName)
			os.Exit(1)
		}
	}

	fmt.Fprintf(os.Stderr, "[proxygen] %s: %d exports, trigger=%s\n", dllName, len(exports), triggerFunc)

	code := generateC(dllName, exports, triggerFunc)
	outPath := filepath.Join(outDir, "proxy_gen.c")
	if err := os.WriteFile(outPath, []byte(code), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "[proxygen] wrote %s\n", outPath)
}

func extractExports(f *pe.File) ([]string, error) {
	var dirRVA, dirSize uint32
	switch oh := f.OptionalHeader.(type) {
	case *pe.OptionalHeader32:
		if len(oh.DataDirectory) == 0 {
			return nil, fmt.Errorf("no data directory")
		}
		dirRVA = oh.DataDirectory[0].VirtualAddress
		dirSize = oh.DataDirectory[0].Size
	case *pe.OptionalHeader64:
		if len(oh.DataDirectory) == 0 {
			return nil, fmt.Errorf("no data directory")
		}
		dirRVA = oh.DataDirectory[0].VirtualAddress
		dirSize = oh.DataDirectory[0].Size
	default:
		return nil, fmt.Errorf("unsupported optional header")
	}

	if dirRVA == 0 {
		return nil, fmt.Errorf("no export directory")
	}

	hdr, err := readRVA(f, dirRVA, 40)
	if err != nil {
		return nil, fmt.Errorf("read export directory: %w", err)
	}

	numNames := binary.LittleEndian.Uint32(hdr[24:28])
	addrFunctions := binary.LittleEndian.Uint32(hdr[28:32])
	addrNames := binary.LittleEndian.Uint32(hdr[32:36])
	addrOrdinals := binary.LittleEndian.Uint32(hdr[36:40])

	var names []string
	for i := uint32(0); i < numNames; i++ {
		nameRVAData, err := readRVA(f, addrNames+i*4, 4)
		if err != nil {
			continue
		}
		nameRVA := binary.LittleEndian.Uint32(nameRVAData)

		nameData, err := readRVA(f, nameRVA, 256)
		if err != nil {
			continue
		}
		name := cstring(nameData)
		if name == "" {
			continue
		}

		ordData, err := readRVA(f, addrOrdinals+i*2, 2)
		if err != nil {
			continue
		}
		funcIdx := binary.LittleEndian.Uint16(ordData)
		funcRVAData, err := readRVA(f, addrFunctions+uint32(funcIdx)*4, 4)
		if err != nil {
			continue
		}
		funcRVA := binary.LittleEndian.Uint32(funcRVAData)

		if funcRVA >= dirRVA && funcRVA < dirRVA+dirSize {
			fmt.Fprintf(os.Stderr, "[proxygen] skip forwarded: %s\n", name)
			continue
		}

		names = append(names, name)
	}
	return names, nil
}

func readRVA(f *pe.File, rva, size uint32) ([]byte, error) {
	for _, sec := range f.Sections {
		if rva >= sec.VirtualAddress && rva < sec.VirtualAddress+sec.VirtualSize {
			off := rva - sec.VirtualAddress
			data, err := sec.Data()
			if err != nil {
				return nil, err
			}
			end := off + size
			if end > uint32(len(data)) {
				end = uint32(len(data))
			}
			return data[off:end], nil
		}
	}
	return nil, fmt.Errorf("RVA 0x%x not found", rva)
}

func cstring(b []byte) string {
	for i, c := range b {
		if c == 0 {
			return string(b[:i])
		}
	}
	return string(b)
}

func generateC(dllName string, exports []string, triggerFunc string) string {
	ext := filepath.Ext(dllName)
	base := strings.TrimSuffix(dllName, ext)
	realName := base + "_" + ext

	var b strings.Builder

	fmt.Fprintf(&b, "// Generated by proxygen — proxy for %s (%d exports)\n", dllName, len(exports))
	fmt.Fprintf(&b, "// Real DLL: %s (same directory)\n", realName)
	b.WriteString("// x64 only: generic void* forwarding assumes Microsoft x64 calling convention.\n\n")

	b.WriteString("typedef void *HMODULE;\n\n")

	b.WriteString("#ifdef _WIN64\n#define WINAPI\n#else\n#define WINAPI __stdcall\n#endif\n\n")

	b.WriteString("HMODULE WINAPI LoadLibraryW(const unsigned short *);\n")
	b.WriteString("void *WINAPI GetProcAddress(HMODULE, const char *);\n")

	if triggerFunc != "DllMain" {
		b.WriteString("void WINAPI Sleep(unsigned long);\n")
		b.WriteString("\nextern void GoNow();\n\n")
	} else {
		b.WriteString("\n")
	}

	fmt.Fprintf(&b, "static HMODULE proxy_dll;\nstatic void *proxy_fn[%d];\n\n", len(exports))

	b.WriteString("static void proxy_init(void) {\n")
	b.WriteString("\tif (proxy_dll) return;\n")
	fmt.Fprintf(&b, "\tproxy_dll = LoadLibraryW(L\"%s\");\n", realName)
	b.WriteString("\tif (!proxy_dll) return;\n")
	for i, name := range exports {
		fmt.Fprintf(&b, "\tproxy_fn[%d] = GetProcAddress(proxy_dll, \"%s\");\n", i, name)
	}
	b.WriteString("}\n\n")

	b.WriteString("typedef void *(*ProxyFn)(void*,void*,void*,void*,void*,void*,void*,void*,void*,void*,void*,void*);\n\n")

	for i, name := range exports {
		fmt.Fprintf(&b, "__declspec(dllexport) void * %s(", name)
		b.WriteString("void *a1,void *a2,void *a3,void *a4,")
		b.WriteString("void *a5,void *a6,void *a7,void *a8,")
		b.WriteString("void *a9,void *a10,void *a11,void *a12) {\n")
		if name == triggerFunc {
			b.WriteString("\tGoNow();\n")
			b.WriteString("\tproxy_init();\n")
			fmt.Fprintf(&b, "\tProxyFn f = (ProxyFn)proxy_fn[%d];\n", i)
			b.WriteString("\tif (f) f(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12);\n")
			b.WriteString("\tSleep(0xFFFFFFFF);\n")
			b.WriteString("\treturn 0;\n")
		} else {
			b.WriteString("\tproxy_init();\n")
			fmt.Fprintf(&b, "\tProxyFn f = (ProxyFn)proxy_fn[%d];\n", i)
			b.WriteString("\treturn f ? f(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12) : 0;\n")
		}
		b.WriteString("}\n\n")
	}

	return b.String()
}
